module.exports = {
  title: "Saudade",
  year: new Date().getFullYear(),
  description: "A community platform for graduate students. Honest stories, quiet solidarity, and the feeling you are not alone.",
  url: "https://saudade.netlify.app",
  author: "Saudade",
  email: "hellosaudade20@gmail.com",
  formspreeId: "xlgypekv",
  nav: [
    { label: "Home", url: "/" },
    { label: "Journal", url: "/journal/" },
    { label: "Stories", url: "/stories/" },
    { label: "Resources", url: "/resources/" },
    { label: "About", url: "/about/" },
    { label: "Contact", url: "/contact/" },
  ],
  categories: [
    "Monthly Reflection",
    "Research Life",
    "Burnout and Recovery",
    "Impostor Syndrome",
    "Identity and Belonging",
    "Letter to My Younger Self",
    "Graduate School Lessons",
    "Life Outside Academia",
    "Personal Growth",
    "Loneliness and Community",
  ],
  storyTopics: [
    "Burnout",
    "Impostor Syndrome",
    "Research Struggles",
    "Advisor Challenges",
    "International Student Experience",
    "Anxiety and Mental Health",
    "Loneliness",
    "Identity and Belonging",
    "Success and Growth",
    "Something Else",
  ],
  resourceCategories: [
    { label: "Crisis Support", icon: "🆘" },
    { label: "Mental Health", icon: "💙" },
    { label: "Books", icon: "📚" },
    { label: "Podcasts", icon: "🎙️" },
    { label: "Academic Wellness", icon: "🌱" },
    { label: "Research Productivity", icon: "🔬" },
  ],
};
